### ISSUE TITLE
Notifications are not enabled on Chrome?

### ISSUE THREAD

**Issue by laclance** [sagiegurari/simple-web-notification#1]
#### Problem Description
HI there, I get notifications are not enabled error even when they are enabled. After researching it might only be possible to display notification on chrome using a server. Can this library work client side with Chrome?

#### Code Example
Same as docs.

**Comment by sagiegurari** [comment]
Its possible you didn't enable the web notifications when the popup came up.
You can setup the site settings in chrome.
Also if you are using files and not http, its possible chrome doesn't enable web notifications.
You didn't give enough info to give a better answer.

also, this is a client only library (browser) and it is not meant for server side (node.js).
you can also look at old closed cases from the original repo for more answers:
https://github.com/sagiegurari/angular-web-notification/issues?q=is%3Aissue+is%3Aclosed

if you don't find anything useful or have more info, please add it.

**Comment by sagiegurari** [comment]
closing due to lack of feedback

**Comment by rayfoss** [comment]
On the mac you have to make sure that "Do not disturb" isn't enabled
