### ISSUE TITLE
What is key of webnotification in service worker?

### ISSUE THREAD

**Issue by stantoxt** [sagiegurari/simple-web-notification#10]
I don't know the service worker example webnotification.And I have a problem,when the notification is show float at screen,the click event will open the a tab with correct url,but when it is picked up in action center,the click event will open the a tab with the only domain.

**Comment by sagiegurari** [comment]
you define what the action does. did you look at the mdn docs for web notifications?

**Comment by stantoxt** [comment]
The code is like the example,
```
{
   body: 'body',
   onClick: function onNotificationClicked() {
       window.open(`https://aaa.com/ClientApp`);
    },
    autoClose: 0
}
```

**Comment by sagiegurari** [comment]
strange, it should open with the resource as well. but thats not really related to this library exactly and you might have a different issue

**Comment by stantoxt** [comment]
thanks, @sagiegurari,I will read mdn deeply.
