### ISSUE TITLE
no main on .bower.json

### ISSUE THREAD

**Issue by fguille94** [sagiegurari/simple-web-notification#11]
**Describe the bug**
My AngularJS `grunt build` is failing due to this package not having a main attribute on its bower.json file

**To Reproduce**
WireDep removes packages from the index.html if they do not meet certain criteria, and it's the "main" attribute on the "bower.json" or ".bower.json" file of each package dependency.

**Workaround**
Manually installed simple-web-notification:1.0.32 which is the latest that worked for me because it does have the "main" attribute with value "web-notification.js" and wiredep will work with it, but upon rerunning bower install it is replaced with 2.0.0 due to some other packages dependencies with this one!

**Comment by sagiegurari** [comment]
ya, i released version 2 which has a breaking change (that's why its a major version change) in which i deleted the bower.json completely.
since bower is dead for around 3 years, i feel we should stop using it :)
there are alternatives like npm/yarn/webpack.
anyhow, i will update the readme and remove bower from there.

**Comment by sagiegurari** [comment]
thinking about it more... i could just add the bower.json back, but not use it myself.
this would unbreak you and won't really impact anything in the library itself....
give me few minutes...

**Comment by sagiegurari** [comment]
version 2.0.1 release. it should resolve your issues, but in general you should move away from bower.
please tell me if its resolve.

**Comment by sagiegurari** [comment]
think this should be resolved.
got no feedback.
closing.
