### ISSUE TITLE
Live demo error

### ISSUE THREAD

**Issue by casaulenbo** [sagiegurari/simple-web-notification#13]
I try to run live demo but not success, please fixed it.
Thank you!

![image](https://user-images.githubusercontent.com/13622862/101865172-24a0e200-3ba8-11eb-99b6-90f4eef46e96.png)

**Comment by sagiegurari** [comment]
seems to load well for me. are you sure its not some local network issue?

**Comment by casaulenbo** [comment]
Good afternoon!

I run it again with Microsoft Edge then it seems to work.
But Google Chrome Version 87.0.4280.88 (Official Build) (64-bit) does not.
![image](https://user-images.githubusercontent.com/13622862/101876939-d8fa3280-3bbf-11eb-99db-a987155ee911.png)

Any extra setting needed?

**Comment by sagiegurari** [comment]
strange. i ran it today on my chrome mobile. i wonder whats blocking those urls on your browser. later today I'll check on a desktop chrome but I don't expect it to behave differently than mobile chrome.

**Comment by casaulenbo** [comment]
Does it useful? 
![image](https://user-images.githubusercontent.com/13622862/101878904-fed50680-3bc2-11eb-9e6c-334ba440608e.png)

**Comment by sagiegurari** [comment]
thats actually ok, but i just checked chrome desktop and it works well.
its possible that you have some local issue or maybe didn't provide permissions/running in incognito (very unlikely).
anyway, suggest you just try it out locally in your local project and it should be ok as the demo works for me on desktop and mobile.

**Comment by casaulenbo** [comment]
Thank you, i will take a try with local environment.

**Comment by t0mtaylor** [comment]
Safari doesn't support `ServiceWorkerRegistration.showNotification()` so then we have the following error:

> `TypeError: serviceWorkerRegistration.showNotification is not a function. (In 'serviceWorkerRegistration.showNotification(title, options)', 'serviceWorkerRegistration.showNotification' is undefined)`

Without registering the service worker it is OK - may need to do browser/feature detection:

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification

![sw-notify-browser-support](https://user-images.githubusercontent.com/975744/101988686-1085df00-3c93-11eb-99e3-49530dceb71c.png)

**Comment by sagiegurari** [comment]
i would expect that on safari the sw won't be provided. i can do the check myself internally but the actions would be ignored and that might be unexpected behavior. no?
