### ISSUE TITLE
onclick doesn't work sometimes

### ISSUE THREAD

**Issue by ShowmanStone** [sagiegurari/simple-web-notification#14]
Hi,
I add onClick function in showNotification just like the example, but when i click the notification, sometimes it doesn't go into the onClick function, but just open a new tab in my chrome and jump to my host page(which is nginx main page), my chrome version is 75.0.
Looking forward to your reply!

**Comment by sagiegurari** [comment]
you gave me no info or code or anything so i'm not sure what you expect me to try to do at this moment.
all i can say, that i don't do much with onclick and pass it to the browser API so if it doesn't work, its 99.999% not this library issue.

**Comment by ShowmanStone** [comment]
sorry for not showing the code as i thought it's nothing special. the code is below:

`window.webNotification = require('../../bower_components/simple-web-notification/web-notification');
 var hideNotification;
 window.webNotification.showNotification(title, {
                                            body: message,
                                            tag: 'rfqRequest',
                                            onClick: function onNotiClicked() {
                                            console.log('notification clicked');
                                            hideNotification && hideNotification();
                                            }
                                            autoClose: 5000
                                        }, function(error, hide) { hideNotification = hide; }
`

and I agree it's probably not this library issue, I just want to know if you have meet this problem before and get some advise.

**Comment by sagiegurari** [comment]
The onclick is just passed to the notification object:
https://github.com/sagiegurari/simple-web-notification/blob/fb94ff835c97937c567f32235003494a5955dcf4/web-notification.js#L181

you are missing a comma before the autoClose but i suppose its not really copy paste from your codebase.
i can't think of a reason it would fail and i never saw such issue before.

worth searching general web notification issue, but it feels strange that this would happen.
i'm guessing the page is still there when the notification is shown right?
