### ISSUE TITLE
Closed window notification supported?

### ISSUE THREAD

**Issue by pwFoo** [sagiegurari/simple-web-notification#2]
I'm searching for a lib with closed window notification support for background running browsers or android devices.
Has simple-web-notification that feature?

**Comment by sagiegurari** [comment]
I guess you want it in your serviceworker. I do have an example of such support in the main readme.
if you want it offline, you might have to bundle it with your service worker js file (never tried that but should work).

**Comment by pwFoo** [comment]
Is it possible to push different notifications to different users? Global namespace sounds like notifications to all subscribers?

**Comment by sagiegurari** [comment]
this library has to do with the notification api which you invoke based on the push event that you listen to. so I do not understand the question

**Comment by pwFoo** [comment]
Ok, I haven't understand how it works. I'm new with the api.
I try to push notifications about updates to subscribed users. Users should only notified about content with the right permissions or content shared with the specific user.

But it looks like Android isn't supported. 
I think I have to search for another solutio

Thanks for answer my questions.

**Comment by pwFoo** [comment]
@sagiegurari 
Your demo doesn't work with my android device. OnePlus5, Chrome. 
Notifications enabled / allowed, but nothing happens.

**Comment by sagiegurari** [comment]
strange, I'll check to see what changed lately in chrome for mobile.

**Comment by sagiegurari** [comment]
see #4
