### ISSUE TITLE
Demo doesn't work with android device 

### ISSUE THREAD

**Issue by pwFoo** [sagiegurari/simple-web-notification#4]
Demo works fine with desktop chrome / edge, but no notification with android / mobile chrome?

**Comment by sagiegurari** [comment]
yes something changed and I will check it. mobile firefox works. I'll investigate

**Comment by sagiegurari** [comment]
found the issue. it seems that now on chrome mobile, you MUST use service workers to display notifications and my demo page doesn't use that. 
so in your case, use the service worker example i have in the readme and you should be all set.
not sure why google did that. its not in any spec that i'm aware of, and firefox doesn't make you do it. 
very very strange.

**Comment by sagiegurari** [comment]
a new version released with improved error handling for chrome mobile and fixed demo page to support that.
you don't have to use the new version, but just make sure to use service worker on chrome mobile.
you can look at the updated example code.
I'll leave this issue open so you will have time to review it.

**Comment by pwFoo** [comment]
Demo works now with chrome mobile. Thanks!
