### ISSUE TITLE
Convert to Push API with VAPID?

### ISSUE THREAD

**Issue by rayfoss** [sagiegurari/simple-web-notification#7]
#### Problem Description
Web Notifications API support is poor on Android. We can have all of the same functionality with the Push API and have it work on Android and ostensibly iOS when apple stops hamstringing the web.

#### Code Example
https://serviceworke.rs/push-get-payload_server_doc.html

**Comment by rayfoss** [comment]
Looks like caniuse might be wrong... it says you can't use the Web Notifications API at all... but I just tried it and it worked https://caniuse.com/#feat=notifications

**Comment by sagiegurari** [comment]
that's because it only works from service worker context. see my demo code

**Comment by rayfoss** [comment]
Which is the right way to do them... on a separate thread. What's wrong is marking it red and saying `Chrome for Android supports notifications via the Push API but not the Web Notifications API.`

**Comment by sagiegurari** [comment]
its not push api. push talks about push events from server to your browser

**Comment by rayfoss** [comment]
Does that not look wrong to you?
![screen shot 2018-08-14 at 11 04 16 am](https://user-images.githubusercontent.com/876076/44103610-4fd198b4-9fb2-11e8-9f83-f9d61fd7bc79.png)

P.S. how can I communicate that I am not a web noob... I had a similar encounter with Paul Irish https://twitter.com/FossPrime/status/1023680966823489537

**Comment by sagiegurari** [comment]
hmmm .... strange

**Comment by rayfoss** [comment]
They fixed it!
![screen shot 2018-08-21 at 9 35 14 am](https://user-images.githubusercontent.com/876076/44408255-a70fbe80-a525-11e8-89aa-b74ddca65bfe.png)

Wonder if we could hijack the background sync API to occasionally send notifications in the background. As the use for this on mobile is a bit hard to justify, the user will have to literally be looking at the app in order to get a notification.

Perhaps this is useful as a space saver... use the real state in the status bar for notifications as opposed to adding UI elements to your app
