### ISSUE TITLE
onclose and onshow listener

### ISSUE THREAD

**Issue by ShowmanStone** [sagiegurari/simple-web-notification#9]
hi,
i wonder why block the onclose and onshow listener as it's very useful and important in some case

**Comment by sagiegurari** [comment]
both events are obsolete. not sure i would want to use/expose those.
see mdn: https://developer.mozilla.org/en-US/docs/Web/API/Notification

**Comment by ShowmanStone** [comment]
ah i didn't notice that,could you pls provide some advice about how i can detect notification is closed by user?

**Comment by sagiegurari** [comment]
I wonder if the onClick I expose would give you that as for simple notifications (without actions), the click will also close it if i'm not wrong.

**Comment by sagiegurari** [comment]
i'm closing this for now as i'm not going to implement those events (and do not recommend for you to use them).
